#!/bin/sh
stagedFiles=$(git diff --staged --name-only)

mvn spotless:apply

for file in $stagedFiles; do
  if test -f "$file" && ! git check-ignore -q "$file" 2>/dev/null; then
    git add $file
  fi
done
