checksumBehavior: update

enableGlobalCache: true

nodeLinker: pnp

pnpEnableInlining: false

npmScopes:
  de-xima:
    npmRegistryServer: "https://artifactory.xima-services.de/artifactory/api/npm/fc-plugin-dev-npm"
    npmAlwaysAuth: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
