checksumBehavior: update

enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  de-xima:
    npmAlwaysAuth: true
    npmRegistryServer: "https://artifactory.xima-services.de/artifactory/api/npm/fc-plugin-dev-npm"

pnpEnableInlining: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
