checksumBehavior: update

enableGlobalCache: true

nodeLinker: pnp

pnpEnableInlining: false

npmAlwaysAuth: true

npmRegistryServer: "https://artifactory.xima-services.de/artifactory/api/npm/npm-fs"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
