function e() {
  window.codbi.loadConfig({
    targets: ".CodBi_People_Alphanumeric",
    FUNC: "HTML.Input.Regex",
    Expression: "\xB0[-0-9A-za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF/:# ]*[0-9A-za-z]$",
    KeyExpression: "[-0-9A-za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF/:# ]",
    Flags: "i",
    ErrorPrefix: "Der Name muss dem regul\xE4ren Ausdruck",
    ErrorPostfix: "entsprechen.",
    ExposeExpression: "TRUE",
  }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_Name",
      FUNC: "HTML.Input.Regex",
      Expression: "\xB0[-A-za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF' ]*[a-z\xE0-\xFF']$",
      KeyExpression: "[ A-Za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF'-]",
      ErrorPrefix: "Der Name muss dem regul\xE4ren Ausdruck",
      ErrorPostfix: "entsprechen.",
      ExposeExpression: "TRUE",
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_BuildingNumber ~ .CodBi_People_OpenPLZ_AC_SET_BuildingNumber",
      FUNC: "HTML.Input.Regex",
      Expression: "\xB0[0-9]([0-9A-Za-z/-]*[0-9A-Za-z])?$",
      KeyExpression: "[-A-Za-z0-9/ ]",
      Flags: "i",
      ErrorPrefix: "Die Hausnummer muss dem regul\xE4ren Ausdruck",
      ErrorPostfix: "entsprechen.",
      ExposeExpression: "TRUE",
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_Mail",
      FUNC: "HTML.Input.Regex",
      Expression: "\xB0[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z][a-zA-Z]?$",
      KeyExpression: "[a-zA-Z0-9._%+-@]",
      Flags: "i",
      ErrorPrefix: "Die Mailadresse muss dem regul\xE4ren Ausdruck",
      ErrorPostfix: "entsprechen.",
      ExposeExpression: "TRUE",
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_Phone",
      FUNC: "HTML.Input.Cleave",
      config: `^${JSON.stringify({ phone: !0, phoneRegionCode: "DE" }).replace("{", "<").replace("}", ">")}`,
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_PLZ",
      FUNC: "HTML.Input.Cleave",
      config: `^${JSON.stringify({ numeral: !0, numeralIntegerScale: 5, delimiter: "" }).replace("{", "<").replace("}", ">")}`,
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_18plus",
      FUNC: "HTML.Input.Cleave, Date.Min",
      Minimum: "18",
      MsgHigher: "18 Jahre ist das erforderliche Mindestalter.",
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_People_16plus",
      FUNC: "HTML.Input.Cleave, Date.Min",
      Minimum: "16",
      MsgHigher: "16 Jahre ist das erforderliche Mindestalter.",
    }),
    window.codbi.loadConfig({
      targets: ".CodBi_Fotocropper",
      FUNC: "Media.Image.Cropper",
      Container: ".CodBi_Fotocropper_Board",
      File: ".CodBi_Fotocropper_Uploader",
      Updater: ".CodBi_Fotocropper_Update",
      ImageURL: ".CodBi_Fotocropper_ImageURL",
      Target: ".CodBi_Fotocropper_Foto",
      AspectRatio: "4 / 3",
    }),
    window.codbi.loadConfigs([
      {
        targets: ".CodBi_People_OpenPLZ_AC_SET_PLZ",
        FUNC: "OpenPLZ.Autocomplete, HTML.Input.Cleave",
        Country: "{ V > CodBi_OpenPLZ_Country }",
        TargetData: "PostalCodes",
        Dependent: ".CodBi_People_OpenPLZ_AC_SET_Locality",
        FocusOnAutocomplete: ".CodBi_People_OpenPLZ_AC_SET_Street",
        MsgNotKnown: "Nur bekannte Postleitzahlen sind zul\xE4ssig.",
        config: `^${JSON.stringify({ numeral: !0, numeralIntegerScale: 5, delimiter: "" }).replace("{", "<").replace("}", ">")}`,
      },
      {
        targets: ".CodBi_People_OpenPLZ_AC_SET_Locality",
        FUNC: "OpenPLZ.Autocomplete, HTML.Input.Regex",
        Country: "{ V > CodBi_OpenPLZ_Country }",
        TargetData: "Localities",
        Dependent: ".CodBi_People_OpenPLZ_AC_SET_PLZ",
        FocusOnAutocomplete: ".CodBi_People_OpenPLZ_AC_SET_Street",
        MsgNotKnown: "Nur bekannte \xD6rtlichkeiten sind zul\xE4ssig.",
        Expression: "\xB0[-A-za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF' ]*[a-z\xE0-\xFF']$",
        KeyExpression: "[ A-Za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF'-]",
        ErrorPrefix: "Der Name muss dem regul\xE4ren Ausdruck",
        ErrorPostfix: "entsprechen.",
        ExposeExpression: "TRUE",
      },
      {
        targets: ".CodBi_People_OpenPLZ_AC_SET_Street",
        FUNC: "OpenPLZ.Autocomplete, HTML.Input.Regex",
        Country: "{ V > CodBi_OpenPLZ_Country }",
        TargetData: "Streets",
        DependentLocality: ".CodBi_People_OpenPLZ_AC_SET_Locality",
        DependentPLZ: ".CodBi_People_OpenPLZ_AC_SET_PLZ",
        FocusOnAutocomplete: ".CodBi_People_OpenPLZ_AC_SET_BuildingNumber",
        MsgNotKnown: "Nur bekannte Stra\xDFen sind zul\xE4ssig.",
        Expression: "\xB0[-A-za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF' ]*[a-z\xE0-\xFF']$",
        KeyExpression: "[ A-Za-z\xC4\xDC\xD6\xE4\xFC\xF6\xDF\xE0-\xFF'-]",
        ErrorPrefix: "Der Name muss dem regul\xE4ren Ausdruck",
        ErrorPostfix: "entsprechen.",
        ExposeExpression: "TRUE",
      },
    ]),
    window.codbi.loadConfigs([
      {
        targets: ".CodBi_People_OpenPLZ_Select_Localities",
        FUNC: "HTML.Select.Injection",
        Values:
          "{ unique > { openplz.localities > { V > CodBi_OpenPLZ_Country };{ V > CodBi_OpenPLZ_Selection_Localities_regexName ; REPORT }; 1 }; name }",
        TitleProperty: "name",
        ValueProperty: "name",
        TextProperty: "name",
      },
      {
        targets: ".CodBi_People_OpenPLZ_Select_Streets_By_PLZ",
        FUNC: "HTML.Select.Injection",
        Values:
          "{ unique > { openplz.streets > { V > CodBi_OpenPLZ_Country };{ V > CodBi_OpenPLZ_Selection_Streets_regexName ; REPORT };{ V > CodBi_OpenPLZ_Selection_Streets_PLZ ; REPORT }}; name }",
        TitleProperty: "name",
        ValueProperty: "name",
        TextProperty: "name",
      },
      {
        targets: ".CodBi_People_OpenPLZ_Select_Orga_Bundeslaender",
        FUNC: "HTML.Select.Injection",
        Values: "{ unique > { openplz.OrganizationalUnits > de ; FederalStates }; name }",
        TitleProperty: "name",
        ValueProperty: "name",
        TextProperty: "name",
      },
      {
        targets: ".CodBi_People_OpenPLZ_Select_Orga_Bayern",
        FUNC: "HTML.Select.Injection",
        Values: "{ unique > { openplz.OrganizationalUnits > de ; FederalStates ; 09 ; GovernmentRegions }; name }",
        TitleProperty: "name",
        ValueProperty: "name",
        TextProperty: "name",
      },
    ]);
}
e();
export { e as loadConfig };
