// ======================================================================
// This file was generated automatically. Do not edit this file manually!
// ======================================================================
package com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.model

/** This enum was generated automatically. Do not edit manually. */
enum class CodbiConfigTemplate(val value: String) {
  DEFAULT("default"),
  XTENSIBLE("xtensible"),
}
