// ======================================================================
// This file was generated automatically. Do not edit this file manually!
// ======================================================================
package com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.model

/** This class was generated automatically. Do not edit manually. */
object Constants {
  const val APIDOC_DIALOG_INPUT_LABEL_PREFIX = "codbi-prop-apiDoc-dialog-input-label-prefix"
  const val DESIGNER_CATEGORY_CODBI_PANEL = "codbi-cat-main"
  const val DESIGNER_CATEGORY_CODBI_PANEL_HELP = "https://github.com/XIMA-formcycle-Entwicklerkreis/CodBi-Dev"
  const val DESIGNER_PROPERTY_CONFIG_TEMPLATE = "codbi-prop-config-template"
  const val DESIGNER_PROPERTY_CONFIG_TEMPLATE_DEFAULT = "default"
  const val DESIGNER_PROPERTY_ENABLE_CODBI = "codbi-prop-enable"
  const val DESIGNER_PROPERTY_ENABLE_CODBI_DEFAULT = "0"
  const val DESIGNER_PROPERTY_STANDARDS = "codbi-prop-standards"
  const val DESIGNER_PROPERTY_STANDARDS_DEFAULT = "Holistic.CSS.Standard"
  const val PLUGIN_FORM_DESIGNER_RESOURCE_ID = "com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.CodbiFormDesignerResource"
  const val PLUGIN_FORM_PROPERTIES_EXTENSION_ID = "com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.CodbiFormPropertiesExtension"
  const val PLUGIN_FORM_RENDER_CALLBACK_ID = "com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.CodbiFormRenderCallback"
  const val PLUGIN_FORM_RESOURCES_ID = "com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.CodbiFormResources"
  const val PLUGIN_KEY = "f140090d-d471-4650-8fef-8067e1e1dcdd"
  const val RESOURCE_PATH_BASE = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/"
  const val RESOURCE_PATH_BUNDLE = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/i18n"
  const val RESOURCE_PATH_CODBI_CONFIG_TEMPLATE_SCRIPT = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/config-template-%s.js"
  const val RESOURCE_PATH_CODBI_CSS = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/codbi.css"
  const val RESOURCE_PATH_CODBI_SCRIPT = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/codbi.js"
  const val RESOURCE_PATH_DESIGNER_FRAME_CSS = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/designer-frame.css"
  const val RESOURCE_PATH_DESIGNER_SCRIPT = "/com/github/xima_formcycle_entwicklerkreis/fc/plugin/codbi/designer.js"
}
