// ======================================================================
// This file was generated automatically. Do not edit this file manually!
// ======================================================================
package com.github.xima_formcycle_entwicklerkreis.fc.plugin.codbi.model

/** This enum was generated automatically. Do not edit manually. */
enum class EMessageKey(val value: String) {
  APIDOC_DIALOG_INPUT_LABEL_PREFIX("apiDoc.dialog.input.label.prefix"),
  DESIGNER_CATEGORY_CODBI_PANEL("designer.category.codbi_panel"),
  DESIGNER_PROPERTY_CONFIG_TEMPLATE("designer.property.config_template"),
  DESIGNER_PROPERTY_CONFIG_TEMPLATE_OPTION_DEFAULT("designer.property.config_template.option.default"),
  DESIGNER_PROPERTY_CONFIG_TEMPLATE_OPTION_XTENSIBLE("designer.property.config_template.option.xtensible"),
  DESIGNER_PROPERTY_ENABLE_CODBI("designer.property.enable_codbi"),
  DESIGNER_PROPERTY_STANDARDS("designer.property.standards"),
  FORM_TEST_STRING("form.test_string"),
  PLUGIN_FORM_DESIGNER_RESOURCE_DESC("plugin.form_designer_resource.desc"),
  PLUGIN_FORM_DESIGNER_RESOURCE_NAME("plugin.form_designer_resource.name"),
  PLUGIN_FORM_PROPERTIES_EXTENSION_DESC("plugin.form_properties_extension.desc"),
  PLUGIN_FORM_PROPERTIES_EXTENSION_NAME("plugin.form_properties_extension.name"),
  PLUGIN_FORM_RENDER_CALLBACK_DESC("plugin.form_render_callback.desc"),
  PLUGIN_FORM_RENDER_CALLBACK_NAME("plugin.form_render_callback.name"),
  PLUGIN_FORM_RESOURCES_DESC("plugin.form_resources.desc"),
  PLUGIN_FORM_RESOURCES_NAME("plugin.form_resources.name"),
}
